### ISSUE TITLE
Incompatible with Python3.6

### ISSUE THREAD

**Issue by ZulwiyozaPutra** [intelie/django-oidc-auth#12]
```
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/oidc_auth/models.py", line 4, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'
(eventory) Taylor:eventory zulwiyozaputra$ python3 manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/oidc_auth/models.py", line 8, in <module>
    from jwkest.jwk import load_jwks_from_url
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/jwkest/__init__.py", line 12, in <module>
    from itertools import izip
ImportError: cannot import name 'izip'
(eventory) Taylor:eventory zulwiyozaputra$ pip install djngo-oidc-auth
Collecting djngo-oidc-auth
  Could not find a version that satisfies the requirement djngo-oidc-auth (from versions: )
No matching distribution found for djngo-oidc-auth
(eventory) Taylor:eventory zulwiyozaputra$ pip install django-oidc-auth
Requirement already satisfied: django-oidc-auth in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages
Requirement already satisfied: requests in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from django-oidc-auth)
Requirement already satisfied: Django>=1.5 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from django-oidc-auth)
Requirement already satisfied: South==1.0.2 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from django-oidc-auth)
Requirement already satisfied: pyjwkest==0.6.2 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from django-oidc-auth)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from requests->django-oidc-auth)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from requests->django-oidc-auth)
Requirement already satisfied: idna<2.7,>=2.5 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from requests->django-oidc-auth)
Requirement already satisfied: certifi>=2017.4.17 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from requests->django-oidc-auth)
Requirement already satisfied: pytz in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from Django>=1.5->django-oidc-auth)
Requirement already satisfied: pycrypto>=2.6.1 in /Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages (from pyjwkest==0.6.2->django-oidc-auth)
(eventory) Taylor:eventory zulwiyozaputra$ python2 manage.py makemigrations
  File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax
(eventory) Taylor:eventory zulwiyozaputra$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/zulwiyozaputra/.virtualenvs/eventory/lib/python3.6/site-packages/oidc_auth/models.py", line 4, in <module>
    from urlparse import urljoin
ModuleNotFoundError: No module named 'urlparse'

```

**Comment by Ipv6Python** [comment]
This is a straight forward client, It will help if this supports Python 3.6 & above.
